CREATE TABLE [AgentTransferFTPImport] (
  [AgentNumber] LONG,
  [ThisAgentName] VARCHAR (255),
  [Add1] VARCHAR (255),
  [Add2] VARCHAR (255),
  [Add3] VARCHAR (255),
  [Adv3] VARCHAR (255),
  [Sysfile_Phone] VARCHAR (255),
  [BlankLines] LONG,
  [CurrShiftDate] DATETIME,
  [SalesTaxRate] CURRENCY,
  [Cr1Installed] LONG,
  [Cr2Installed] LONG,
  [Cr3Installed] LONG,
  [Cr4Installed] LONG,
  [Cr1Online] LONG,
  [Cr2Online] LONG,
  [Cr3Online] LONG,
  [Cr4Online] LONG,
  [Cr1CheckOut] LONG,
  [Cr2CheckOut] LONG,
  [Cr3CheckOut] LONG,
  [Cr4CheckOut] LONG,
  [Online] LONG,
  [CashDropItemID] LONG,
  [CashLoanItemID] LONG,
  [ChargeDropItemID] LONG,
  [CheckDropItemID] LONG,
  [ClubInvItemID] LONG,
  [ClubDiscRate] DOUBLE,
  [ClubDiscntItemID] LONG,
  [CouponItemID] LONG,
  [DiscountItemID] LONG,
  [LotteryPaidOutItemID] LONG,
  [NonClubDiscntItemID] LONG,
  [NonClubDiscRate] DOUBLE,
  [NonClubInvItemID] LONG,
  [CancelTenderID] LONG,
  [NoSaleTenderID] LONG,
  [ScannedODLTenderID] LONG,
  [ReportsDir] VARCHAR (255),
  [CashsysInsLoc] VARCHAR (255),
  [NetworkDataBaseConnectString] VARCHAR (255),
  [NetworkDatabase] VARCHAR (255),
  [NetworkMailDir] VARCHAR (255),
  [OLCCVendor] LONG,
  [InvoiceCounter] LONG,
  [ColorInfo] LONG,
  [ColorDropDown] LONG,
  [ColorViewOnly] LONG,
  [ColorTotals] LONG,
  [ColorLockedForAll] LONG,
  [PrintReceiptCancelledSale] LONG,
  [SetupDate] DATETIME,
  [ChangeDate] DATETIME,
  [ID] LONG,
  [AgentID] LONG,
  [Order] LONG,
  [OrdDate] DATETIME,
  [AgentName] VARCHAR (255),
  [Address] VARCHAR (255),
  [CitySTZ] VARCHAR (255),
  [qryAgentTransferLines_Phone] VARCHAR (255),
  [LineID] LONG,
  [ItemID] VARCHAR,
  [Description] VARCHAR (255),
  [SizeID] LONG,
  [QuantityShipped] LONG,
  [Price] CURRENCY,
  [UPCCodeMax] VARCHAR (255),
  [ExtPrice] CURRENCY,
  [Status] VARCHAR (255),
  [SizeDesc] VARCHAR (255),
  [Cost] CURRENCY,
  [ExtCost] CURRENCY
)
