CREATE TABLE [HourlySales] (
  [Date] VARCHAR (255),
  [SumOfPrice] CURRENCY,
  [10 AM] CURRENCY,
  [11 AM] CURRENCY,
  [12 AM] CURRENCY,
  [1 PM] CURRENCY,
  [2 PM] CURRENCY,
  [3 PM] CURRENCY,
  [4 PM] CURRENCY,
  [5 PM] CURRENCY,
  [6 PM] CURRENCY,
  [7 PM] CURRENCY,
  [8 PM] CURRENCY,
  [9 PM] CURRENCY
)
