CREATE TABLE [InventoryReportParameters] (
  [ReportCategory] VARCHAR (50),
  [ReportName] VARCHAR (50) CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [QueryName] VARCHAR (50),
  [ChartQueryName] VARCHAR (50),
  [RangeSalesDepartments] BIT,
  [RangeSubCategories] BIT,
  [RangeVendor] BIT,
  [RangeLocations] BIT,
  [RangePriceGroupID] BIT,
  [RangeItemID] BIT,
  [RangeDates] BIT,
  [RangeClubs] BIT,
  [PrintOnhands] BIT,
  [PrintCost] BIT,
  [PrintZeroOnhands] BIT,
  [NumericRange] BIT,
  [NumericRangeLeadThru] VARCHAR (50),
  [Description] LONGTEXT,
  [DateFrom] DATETIME,
  [DateTo] DATETIME,
  [SetupDate] DATETIME,
  [ChangeDate] DATETIME
)
