CREATE TABLE [olcc order] (
  [ID] AUTOINCREMENT CONSTRAINT [ID] PRIMARY KEY UNIQUE NOT NULL,
  [ITEM ] DOUBLE,
  [DESCRIPTION] VARCHAR (255),
  [ORDER ] DOUBLE,
  [FACINGS] DOUBLE,
  [Field5] VARCHAR (255)
)
