CREATE TABLE [PurchaseOrderItemWADS] (
  [VendorID] LONG,
  [Name] VARCHAR (25),
  [ItemID] VARCHAR,
  [Description] VARCHAR (50),
  [SizeID] LONG,
  [Onhand] LONG,
  [Ordered] LONG,
  [Reserved] LONG,
  [Avail] LONG,
  [AverageDailySales] DOUBLE,
  [DaysSupply] LONG,
  [OrderMax] LONG,
  [SOQRaw] VARCHAR,
  [OrderMultiple] LONG,
  [SOQ] LONG,
  [UnitsPerCase] LONG,
  [Price] CURRENCY,
  [Sprice] CURRENCY,
  [SPriceStar] VARCHAR (255),
  [ExtPrice] CURRENCY,
  [Cost] CURRENCY,
  [ExtCost] CURRENCY,
  [SalesDepartmentID] LONG,
  [Repack] SHORT,
  [CategoryDescr] VARCHAR (255)
)
