CREATE TABLE [zCashSys] (
  [ID] LONG CONSTRAINT [ID] UNIQUE CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [ShiftCounter] LONG,
  [ComputerName] VARCHAR (50),
  [Description] VARCHAR (255),
  [DrawerPort] VARCHAR (50),
  [DisplayPort] VARCHAR (50),
  [DisplayDefault] VARCHAR (80),
  [PrinterPort] VARCHAR (50),
  [ReportsDir] VARCHAR (50),
  [InvoiceTrailer] VARCHAR (40),
  [AllowExactCh] BIT,
  [AllowEscape] BIT,
  [Reprintnegsales] BIT,
  [EpsonSlitIns] BIT,
  [PrintReceipt] BIT,
  [EpsonPrinterInstalled] BIT,
  [EpsonPrintertSlit] BIT,
  [DropAlertAmt] CURRENCY,
  [LastInvoiceNo] LONG,
  [ReceiptSpaces] SHORT,
  [ClubSmode] LONG,
  [StoreSmode] LONG,
  [OlccSmode] LONG,
  [InvenSmode] LONG,
  [AdjSmode] LONG,
  [XfrSmode] LONG,
  [ScannerComPort] SHORT,
  [ScannerSettings] VARCHAR (20),
  [LogoutTimer] LONG,
  [pcChargeInstalled] BIT,
  [pcChargeDir] VARCHAR (50),
  [pcChargeProcesser] VARCHAR (10),
  [pcChargeMerchantID] VARCHAR (20),
  [pcChargeDefaultDebit] BIT,
  [PrintZReports] BIT,
  [pcChargePinPadComPort] SHORT,
  [pcChargeProcesserRelated] VARCHAR (10),
  [pcChargeMerchantIDRelated] VARCHAR (20),
  [ShowAvail] BIT,
  [PlaySounds] BIT,
  [ShowRemoveItem] BIT,
  [ShowDupeItem] BIT,
  [SetupDate] DATETIME,
  [ChangeDate] DATETIME,
  [upsize_ts] BINARY,
  [DVRProtocol] SHORT,
  [DVRRemoteHost] VARCHAR (20),
  [DVRRemotePort] SHORT,
  [pcChargeUserNo] SHORT,
  [pcChargePinPadTDES] BIT,
  [pcChargeCommMethod] BIT,
  [pcChargeIPAddress] VARCHAR (20),
  [pcChargePort] LONG,
  [pcChargeEnableSSL] BIT,
  [pcChargeAllowHandEnter] BIT
)
