CREATE TABLE [zCashier] (
  [ID] SHORT CONSTRAINT [ID] UNIQUE CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [Name] VARCHAR (20),
  [Password] VARCHAR (10),
  [Security] VARCHAR (1),
  [Drawer] SHORT,
  [ValidRegisters] VARCHAR (8),
  [Manager] BIT,
  [AllowCancelSale] BIT,
  [AllowCashDrops] BIT,
  [AllowCashLoans] BIT,
  [AllowCoupons] BIT,
  [AllowDiscountItem] BIT,
  [AllowLotteryPaidOut] BIT,
  [AllowNegSales] BIT,
  [AllowNewItems] BIT,
  [AllowNoSales] BIT,
  [AllowPaidouts] BIT,
  [AllowSellClub] BIT,
  [AllowShutDown] BIT,
  [AllowViewJournal] BIT,
  [AllowXReports] BIT,
  [AllowZReports] BIT,
  [AllowChangePrice] BIT,
  [AllowChangeOnhand] BIT,
  [AllowChangeCost] BIT,
  [AllowChangeOrderAt] BIT,
  [AllowChangeOrderTo] BIT,
  [AllowChangeDescription] BIT,
  [AllowDeleteDocument] BIT,
  [DailyDropCounter] SHORT,
  [PayrollID] VARCHAR (15),
  [HourlyWage] CURRENCY,
  [AllowHourlyWageView] BIT,
  [DailyPunchCounter] SHORT,
  [SetupDate] DATETIME,
  [ChangeDate] DATETIME,
  [upsize_ts] BINARY,
  [PasswordHistory1] VARCHAR (10),
  [PasswordHistory2] VARCHAR (10),
  [PasswordHistory3] VARCHAR (10),
  [PasswordHistory4] VARCHAR (10),
  [AccountLocked] BIT,
  [AccountLockedDate] DATETIME,
  [PasswordDate] DATETIME
)
