CREATE TABLE [zClub] (
  [ID] LONG CONSTRAINT [ID] UNIQUE CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [Name] VARCHAR (50) CONSTRAINT [Name] UNIQUE,
  [Contact] VARCHAR (50),
  [Address1] VARCHAR (50),
  [Address2] VARCHAR (50),
  [City] VARCHAR (50),
  [St] VARCHAR (2),
  [Zip] VARCHAR (10),
  [Phone1] VARCHAR (50),
  [Phone2] VARCHAR (50),
  [Phone3] VARCHAR (50),
  [OrderCount] LONG,
  [OrderGuides] SHORT,
  [Invoices] SHORT,
  [Picklists] SHORT,
  [NonLiquor] BIT,
  [PosPicks] SHORT,
  [ClubNotes] LONGTEXT,
  [PickListSort] VARCHAR (25),
  [InvoiceListSort] VARCHAR (25),
  [OrderGuideSort] VARCHAR (25),
  [ApplyDiscount] BIT,
  [MaintainParLevels] BIT,
  [OrderGuideByCategory] BIT,
  [InvoiceByCategory] BIT,
  [InvoicesCombined] SHORT,
  [InvoiceCombinedListSort] VARCHAR (25),
  [EMail] VARCHAR (50),
  [Licensee] VARCHAR (15),
  [SetupDate] DATETIME,
  [ChangeDate] DATETIME,
  [StoreInvoices] SHORT,
  [StoreInvoiceSort] VARCHAR (25),
  [OuncesColumn] CURRENCY,
  [ClubOrderGuideReport] VARCHAR (25),
  [upsize_ts] BINARY,
  [FintechAccount] VARCHAR (25)
)
