CREATE TABLE [zItem] (
  [ID] VARCHAR CONSTRAINT [ID] UNIQUE CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [SizeID] LONG,
  [SalesDepartmentID] LONG,
  [VendorID] LONG,
  [PriceGroupID] LONG,
  [SubCategoryID] LONG,
  [Description] VARCHAR (50),
  [Onhand] LONG,
  [OrderAt] LONG,
  [OrderTo] LONG,
  [AvgTurns] LONG,
  [Price] CURRENCY,
  [Cost] CURRENCY,
  [Deposit] CURRENCY,
  [UnitsPerCase] LONG,
  [UnitsPerOrder] LONG,
  [UnitsPerPack] LONG,
  [SubPack] VARCHAR (15),
  [SoldTodayCr1] LONG,
  [SoldTodayCr2] LONG,
  [SoldTodayCr3] LONG,
  [SoldTodayCr4] LONG,
  [SoldTodayCr5] LONG,
  [TransferredToday] LONG,
  [RestockAmount] LONG,
  [Location] VARCHAR (10),
  [QtyPack] LONG,
  [QtyPackPrice] CURRENCY,
  [StockNumber] VARCHAR (20),
  [PLUList] BIT,
  [DateLastSold] DATETIME,
  [TPR] BIT,
  [AverageDailySales] DOUBLE,
  [DaysSupplyGroupID] LONG,
  [SalesLeadID] LONG,
  [PictureID] LONG,
  [SetupDate] DATETIME,
  [ChangeDate] DATETIME,
  [upsize_ts] BINARY
)
