CREATE TABLE [zOrdHead] (
  [ID] AUTOINCREMENT CONSTRAINT [ID] UNIQUE CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [ClubID] LONG,
  [Order] LONG,
  [InvoiceNo] LONG,
  [OrdDate] DATETIME,
  [OrdQty] LONG,
  [OrdDollars] CURRENCY,
  [PickDate] DATETIME,
  [InvDate] DATETIME,
  [InvQty] LONG,
  [InvDollars] CURRENCY,
  [DisDollars] CURRENCY,
  [UpdDate] DATETIME,
  [PaidFlag] BIT,
  [Status] VARCHAR (1),
  [OrderNotes] LONGTEXT,
  [LiquorDollars] CURRENCY,
  [LiquorDiscount] CURRENCY,
  [NonLiquorDollars] CURRENCY,
  [NonLiquorDiscount] CURRENCY,
  [SetupDate] DATETIME,
  [ChangeDate] DATETIME,
  [upsize_ts] BINARY
)
