CREATE TABLE [zSysfile] (
  [ID] SHORT,
  [AgentNumber] LONG,
  [Name] VARCHAR (40),
  [Add1] VARCHAR (40),
  [Add2] VARCHAR (40),
  [Add3] VARCHAR (50),
  [Adv3] VARCHAR (40),
  [Phone] VARCHAR (20),
  [BlankLines] SHORT,
  [CurrShiftDate] VARCHAR (255),
  [SalesTaxRate] CURRENCY,
  [Cr1Installed] BIT,
  [Cr2Installed] BIT,
  [Cr3Installed] BIT,
  [Cr4Installed] BIT,
  [Cr5Installed] BIT,
  [Cr1Online] BIT,
  [Cr2Online] BIT,
  [Cr3Online] BIT,
  [Cr4Online] BIT,
  [Cr5Online] BIT,
  [Cr1CheckOut] BIT,
  [Cr2CheckOut] BIT,
  [Cr3CheckOut] BIT,
  [Cr4CheckOut] BIT,
  [Cr5CheckOut] BIT,
  [Online] BIT,
  [CashDropItemID] LONG,
  [CashLoanItemID] LONG,
  [ChargeDropItemID] LONG,
  [CheckDropItemID] LONG,
  [ClubInvItemID] LONG,
  [ClubDiscRate] DOUBLE,
  [ClubDiscntItemID] LONG,
  [CouponItemID] LONG,
  [DiscountItemID] LONG,
  [LotteryPaidOutItemID] LONG,
  [NonClubDiscntItemID] LONG,
  [NonClubDiscRate] DOUBLE,
  [NonClubInvItemID] LONG,
  [DepositItemID] LONG,
  [CancelTenderID] LONG,
  [NoSaleTenderID] LONG,
  [ScannedODLTenderID] LONG,
  [ReportsDir] VARCHAR (50),
  [CashsysInsLoc] VARCHAR (20),
  [NetworkDataBaseConnectString] VARCHAR (100),
  [NetworkDatabase] VARCHAR (50),
  [NetworkMailDir] VARCHAR (50),
  [OLCCVendor] LONG,
  [InvoiceCounter] LONG,
  [ColorInfo] LONG,
  [ColorDropDown] LONG,
  [ColorViewOnly] LONG,
  [ColorTotals] LONG,
  [ColorLockedForAll] LONG,
  [PrintReceiptCancelledSale] BIT,
  [AKey] LONG,
  [BKey] LONG,
  [CKey] LONG,
  [DKey] LONG,
  [EKey] LONG,
  [FKey] LONG,
  [GKey] LONG,
  [HKey] LONG,
  [IKey] LONG,
  [JKey] LONG,
  [KKey] LONG,
  [LKey] LONG,
  [MKey] LONG,
  [NKey] LONG,
  [OKey] LONG,
  [PKey] LONG,
  [QKey] LONG,
  [RKey] LONG,
  [SKey] LONG,
  [TKey] LONG,
  [UKey] LONG,
  [VKey] LONG,
  [WKey] LONG,
  [XKey] LONG,
  [YKey] LONG,
  [ZKey] LONG,
  [ADD_INVOLINE_COST_AND_INV5LINE_COST] BIT,
  [TransferCartonsToPacks] BIT,
  [RentrakInstalled] BIT,
  [PrintRelatedOnOLCCInvoice] BIT,
  [OLCCFTPServer] VARCHAR (30),
  [OLCCFTPUser] VARCHAR (50),
  [OLCCFTPPassword] VARCHAR (50),
  [OLCCFTPASCII] BIT,
  [OLCCFTPEndOfDaySend] BIT,
  [SetupDate] DATETIME,
  [ChangeDate] DATETIME,
  [upsize_ts] BINARY,
  [PalmDataDirectoryInventoryTo] VARCHAR (100),
  [PalmDataDirectoryInventoryFrom] VARCHAR (100),
  [PalmDataDirectoryPurchaseTo] VARCHAR (100),
  [PalmDataDirectoryPurchaseFrom] VARCHAR (100),
  [AutoDropChecks] BIT,
  [AutoDropCharges] BIT,
  [SaveReportsAsPDF] BIT,
  [ClubExportOGFormatInExcel] BIT
)
