dbMemo "SQL" ="SELECT vwItemsWithCurrentPricing.CategoryDescr, vwItemsWithCurrentPricing.Descri"
    "ption, vwItemsWithCurrentPricing.PkgSize, vwItemsWithCurrentPricing.ID, vwItemsW"
    "ithCurrentPricing.OnShelf, vwItemsWithCurrentPricing.CurPrice, vwItemsWithCurren"
    "tPricing.Cost\015\012FROM vwItemsWithCurrentPricing\015\012ORDER BY vwItemsWithC"
    "urrentPricing.CategoryDescr, vwItemsWithCurrentPricing.Description, vwItemsWithC"
    "urrentPricing.PkgSize;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="0"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
Begin
End
