SELECT
  IIf(
    ([ITEMID] > 99900000000),
    [iTEMID] - 99900000000,
    [ITEMID]
  ) AS STRIPPED,
  qryClubOrderGuidesReport.*,
  Sysfile.AgentNumber,
  Sysfile.Name,
  Sysfile.Add1,
  Sysfile.Add2,
  Sysfile.Add3,
  Sysfile.Adv3,
  Sysfile.Phone,
  Sysfile.BlankLines,
  Sysfile.CurrShiftDate,
  Sysfile.SalesTaxRate,
  Sysfile.Cr1Installed,
  Sysfile.Cr2Installed,
  Sysfile.Cr3Installed,
  Sysfile.Cr4Installed,
  Sysfile.Cr1Online,
  Sysfile.Cr2Online,
  Sysfile.Cr3Online,
  Sysfile.Cr4Online,
  Sysfile.Cr1CheckOut,
  Sysfile.Cr2CheckOut,
  Sysfile.Cr3CheckOut,
  Sysfile.Cr4CheckOut,
  Sysfile.Online,
  Sysfile.CashDropItemID,
  Sysfile.CashLoanItemID,
  Sysfile.ChargeDropItemID,
  Sysfile.CheckDropItemID,
  Sysfile.ClubInvItemID,
  Sysfile.ClubDiscRate,
  Sysfile.ClubDiscntItemID,
  Sysfile.CouponItemID,
  Sysfile.DiscountItemID,
  Sysfile.LotteryPaidOutItemID,
  Sysfile.NonClubDiscntItemID,
  Sysfile.NonClubDiscRate,
  Sysfile.NonClubInvItemID,
  Sysfile.CancelTenderID,
  Sysfile.NoSaleTenderID,
  Sysfile.ScannedODLTenderID,
  Sysfile.ReportsDir,
  Sysfile.CashsysInsLoc,
  Sysfile.NetworkDatabase,
  Sysfile.NetworkMailDir,
  Sysfile.OLCCVendor,
  Sysfile.InvoiceCounter,
  Sysfile.SetupDate,
  Sysfile.ChangeDate,
  qryClubOrderGuidesReport.MaintainParLevels,
  qryClubOrderGuidesReport.Par,
  Format(
    qryClubOrderGuidesReport.LineID,
    "#"
  )& " - " & qryClubOrderGuidesReport.Description AS LineDesc,
  qryClubOrderGuidesReport.Location AS Location,
  qryClubOrderGuidesReport.PricePerShot,
  qryClubOrderGuidesReport.OuncesColumn AS OZColumn
FROM
  Sysfile,
  qryClubOrderGuidesReport;
