dbMemo "SQL" ="UPDATE (qryProductListWithCategoriesFromOLCCWebsite INNER JOIN SubCategory ON qr"
    "yProductListWithCategoriesFromOLCCWebsite.F5=SubCategory.Description) INNER JOIN"
    " Item ON qryProductListWithCategoriesFromOLCCWebsite.Code=Item.ID SET Item.SubCa"
    "tegoryID = SubCategory.ID;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "UseTransaction" ="-1"
dbBoolean "FailOnError" ="0"
dbByte "Orientation" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
Begin
End
