dbMemo "SQL" ="UPDATE ItemMovement SET ItemMovement.CurrMM = 0-[CurrMM], ItemMovement.YTDQty = "
    "0-[YTDQty], ItemMovement.Jan = 0-[Jan], ItemMovement.Feb = 0-[Feb], ItemMovement"
    ".Mar = 0-[Mar], ItemMovement.Apr = 0-[Apr], ItemMovement.May = 0-[May], ItemMove"
    "ment.Jun = 0-[Jun], ItemMovement.Jul = 0-[Jul], ItemMovement.Aug = 0-[Aug], Item"
    "Movement.Sep = 0-[Sep], ItemMovement.Oct = 0-[Oct], ItemMovement.Nov = 0-[Nov], "
    "ItemMovement.[Dec] = 0-[Dec]\015\012WHERE (((ItemMovement.Description)=\"Purchas"
    "es\"));\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "UseTransaction" ="-1"
dbBoolean "FailOnError" ="0"
dbByte "Orientation" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
Begin
End
