dbMemo "SQL" ="PARAMETERS parVendorID Long;\015\012SELECT qryPurchaseOrderItemInfoWithNoOnOrder"
    ".VendorID, qryPurchaseOrderItemInfoWithNoOnOrder.Name, qryPurchaseOrderItemInfoW"
    "ithNoOnOrder.ItemID, qryPurchaseOrderItemInfoWithNoOnOrder.SalesDepartmentID, qr"
    "yPurchaseOrderItemInfoWithNoOnOrder.Description, qryPurchaseOrderItemInfoWithNoO"
    "nOrder.SizeID, qryPurchaseOrderItemInfoWithNoOnOrder.Onhand, qryPurchaseOrderIte"
    "mInfoWithNoOnOrder.Ordered, qryPurchaseOrderItemInfoWithNoOnOrder.Reserved, qryP"
    "urchaseOrderItemInfoWithNoOnOrder.Avail, qryPurchaseOrderItemInfoWithNoOnOrder.O"
    "rderAt, qryPurchaseOrderItemInfoWithNoOnOrder.OrderTo, qryPurchaseOrderItemInfoW"
    "ithNoOnOrder.SOQRaw, qryPurchaseOrderItemInfoWithNoOnOrder.OrderMultiple, qryPur"
    "chaseOrderItemInfoWithNoOnOrder.SOQ, qryPurchaseOrderItemInfoWithNoOnOrder.Units"
    "PerCase, qryPurchaseOrderItemInfoWithNoOnOrder.SPrice, qryPurchaseOrderItemInfoW"
    "ithNoOnOrder.SPriceStar, qryPurchaseOrderItemInfoWithNoOnOrder.ExtPrice, qryPurc"
    "haseOrderItemInfoWithNoOnOrder.Cost, qryPurchaseOrderItemInfoWithNoOnOrder.ExtCo"
    "st, IIf((([soq]\\[UnitsPerCase])*[UnitsPerCase])=[soq],0,-1) AS Repack, qryPurch"
    "aseOrderItemInfoWithNoOnOrder.SPrice, qryPurchaseOrderItemInfoWithNoOnOrder.SPri"
    "ce\015\012FROM qryPurchaseOrderItemInfoWithNoOnOrder\015\012WHERE (((qryPurchase"
    "OrderItemInfoWithNoOnOrder.VendorID)=[parVendorID]) AND ((qryPurchaseOrderItemIn"
    "foWithNoOnOrder.Avail)<=[OrderAt]) AND ((qryPurchaseOrderItemInfoWithNoOnOrder.O"
    "rderTo)>0) AND ((qryPurchaseOrderItemInfoWithNoOnOrder.SOQ)>0));\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
Begin
    Begin
        dbText "Name" ="Repack"
        dbLong "AggregateType" ="-1"
    End
End
