dbMemo "SQL" ="UPDATE ((ConvMIXMASTR INNER JOIN PriceGroup ON ConvMIXMASTR.Desc=PriceGroup.Desc"
    "ription) INNER JOIN ConvITEMS ON ConvMIXMASTR.Code=ConvITEMS.MixmCode) INNER JOI"
    "N Item ON ConvITEMS.Code=Item.ID SET Item.PriceGroupID = PriceGroup.ID;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "UseTransaction" ="-1"
dbBoolean "FailOnError" ="0"
dbByte "Orientation" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
Begin
End
